#EXPERIMENT NUMBER 13
#DATA BINNING AND DATA FORMATTING USING PYTHON
#ROHAN KUMBHAR
#ENTC A2
#25070123141
#23/03/26

In [ ]:
import pandas as pd
import numpy as np
data= {
    'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
    'Price':[55000,20000,30000,2000,8000,45000],
    'Units_sold':[25,60,35,80,50,15]

}
df=pd.DataFrame(data)
print(df)

      Product  Price  Units_sold
0      Laptop  55000          25
1      Mobile  20000          60
2      Tablet  30000          35
3  Headphones   2000          80
4  Smartwatch   8000          50
5      Camera  45000          15

In [ ]:
#Data Binning
bins1=[0,10000,30000,60000]
labels1=['Low','Medium','High']
df['Price_Category']=pd.cut(df['Price'],bins=bins1,labels=labels1)
print(df)

      Product  Price  Units_sold Price_Category
0      Laptop  55000          25           High
1      Mobile  20000          60         Medium
2      Tablet  30000          35         Medium
3  Headphones   2000          80            Low
4  Smartwatch   8000          50            Low
5      Camera  45000          15           High

In [ ]:
bins2=[0,30,60,90]
labels2=['Low sales', 'Mediuum sales','High sales']
df['Sales_Category']=pd.cut(df['Units_sold'],bins=bins2,labels=labels2)
print(df)

      Product  Price  Units_sold Price_Category Sales_Category
0      Laptop  55000          25           High      Low sales
1      Mobile  20000          60         Medium  Mediuum sales
2      Tablet  30000          35         Medium  Mediuum sales
3  Headphones   2000          80            Low     High sales
4  Smartwatch   8000          50            Low  Mediuum sales
5      Camera  45000          15           High      Low sales

In [ ]:
#Data formatting
#Convert data type
print(df.dtypes)
df['Units_sold']=df['Units_sold'].astype(float)
print(df.dtypes)

Product             object
Price                int64
Units_sold           int64
Price_Category    category
Sales_Category    category
dtype: object
Product             object
Price                int64
Units_sold         float64
Price_Category    category
Sales_Category    category
dtype: object

In [ ]:
#Convert text to upercase
df['Product']=df['Product'].str.upper()
print(df)

      Product  Price  Units_sold Price_Category Sales_Category
0      LAPTOP  55000        25.0           High      Low sales
1      MOBILE  20000        60.0         Medium  Mediuum sales
2      TABLET  30000        35.0         Medium  Mediuum sales
3  HEADPHONES   2000        80.0            Low     High sales
4  SMARTWATCH   8000        50.0            Low  Mediuum sales
5      CAMERA  45000        15.0           High      Low sales

In [ ]:
#Rounding Values
df['Price']=df['Price'].round(2)
print(df)

      Product  Price  Units_sold Price_Category Sales_Category
0      LAPTOP  55000        25.0           High      Low sales
1      MOBILE  20000        60.0         Medium  Mediuum sales
2      TABLET  30000        35.0         Medium  Mediuum sales
3  HEADPHONES   2000        80.0            Low     High sales
4  SMARTWATCH   8000        50.0            Low  Mediuum sales
5      CAMERA  45000        15.0           High      Low sales

In [ ]:
#Additional Operations
#Sort Data
sorted_df=df.sort_values(by='Price')
print(sorted_df)

      Product  Price  Units_sold Price_Category Sales_Category
3  HEADPHONES   2000        80.0            Low     High sales
4  SMARTWATCH   8000        50.0            Low  Mediuum sales
1      MOBILE  20000        60.0         Medium  Mediuum sales
2      TABLET  30000        35.0         Medium  Mediuum sales
5      CAMERA  45000        15.0           High      Low sales
0      LAPTOP  55000        25.0           High      Low sales

In [ ]:
#Display unique values
print(df['Price_Category'].unique())

['High', 'Medium', 'Low']
Categories (3, object): ['Low' < 'Medium' < 'High']

In [ ]:
#Dataset: Food Deivery Order
import pandas as pd
import numpy as np
data={
    'Order_ID':['O1','O2','O3','O4','O5','O6','O7','O8'],
    'Order_Value':[250,450,120,600,300,150,500,220],
    'Delivery_Time':[30,45,15,60,25,10,55,35],
    "Customer_Rating":[4,3,2,5,4,3,2,5],
    'Distance_KM':[10,15,5,20,12,8,18,10]
}
df=pd.DataFrame(data)
print(df)

  Order_ID  Order_Value  Delivery_Time  Customer_Rating  Distance_KM
0       O1          250             30                4           10
1       O2          450             45                3           15
2       O3          120             15                2            5
3       O4          600             60                5           20
4       O5          300             25                4           12
5       O6          150             10                3            8
6       O7          500             55                2           18
7       O8          220             35                5           10

In [ ]:
#Bidding Order Values
bin=[0,200,400,700]
labels1=['Low Order','Medium Order','High Order']
df['Order_Value_Category']=pd.cut(df['Order_Value'],bins=bin,labels=labels1)
print(df)

  Order_ID  Order_Value  Delivery_Time  Customer_Rating  Distance_KM  \
0       O1          250             30                4           10
1       O2          450             45                3           15
2       O3          120             15                2            5
3       O4          600             60                5           20
4       O5          300             25                4           12
5       O6          150             10                3            8
6       O7          500             55                2           18
7       O8          220             35                5           10

  Order_Value_Category
0         Medium Order
1           High Order
2            Low Order
3           High Order
4         Medium Order
5            Low Order
6           High Order
7         Medium Order

In [ ]:
#Binning delivery Time
bins2= [0,30,45,70]
labels2=['Fast Delivery','Average Delivery','Slow Delivery']
df['Delivery_Time_Category']=pd.cut(df['Delivery_Time'],bins=bins2,labels=labels2)
print(df)

  Order_ID  Order_Value  Delivery_Time  Customer_Rating  Distance_KM  \
0       O1          250             30                4           10
1       O2          450             45                3           15
2       O3          120             15                2            5
3       O4          600             60                5           20
4       O5          300             25                4           12
5       O6          150             10                3            8
6       O7          500             55                2           18
7       O8          220             35                5           10

  Order_Value_Category Delivery_Time_Category
0         Medium Order          Fast Delivery
1           High Order       Average Delivery
2            Low Order          Fast Delivery
3           High Order          Slow Delivery
4         Medium Order          Fast Delivery
5            Low Order          Fast Delivery
6           High Order          Slow Delivery
7         Medium Order       Average Delivery

In [ ]:
#Data formating examples
#convert distance to float
df['Distance_KM']=df['Distance_KM'].astype(float)
print(df.dtypes)

Order_ID                    object
Order_Value                  int64
Delivery_Time                int64
Customer_Rating              int64
Distance_KM                float64
Order_Value_Category      category
Delivery_Time_Category    category
dtype: object

In [ ]:
#Convert Order_ID TO UPPERCASE
df['Order_Value_Category']=df['Order_Value_Category'].str.upper()
print(df)

  Order_ID  Order_Value  Delivery_Time  Customer_Rating  Distance_KM  \
0       O1          250             30                4         10.0
1       O2          450             45                3         15.0
2       O3          120             15                2          5.0
3       O4          600             60                5         20.0
4       O5          300             25                4         12.0
5       O6          150             10                3          8.0
6       O7          500             55                2         18.0
7       O8          220             35                5         10.0

  Order_Value_Category Delivery_Time_Category
0         MEDIUM ORDER          Fast Delivery
1           HIGH ORDER       Average Delivery
2            LOW ORDER          Fast Delivery
3           HIGH ORDER          Slow Delivery
4         MEDIUM ORDER          Fast Delivery
5            LOW ORDER          Fast Delivery
6           HIGH ORDER          Slow Delivery
7         MEDIUM ORDER       Average Delivery

In [ ]:
#Check datatypes
print(df.dtypes)

Order_ID                    object
Order_Value                  int64
Delivery_Time                int64
Customer_Rating              int64
Distance_KM                float64
Order_Value_Category        object
Delivery_Time_Category    category
dtype: object

In [ ]:
#Unique categories
print(df['Order_Value_Category'].unique())
df

['MEDIUM ORDER' 'HIGH ORDER' 'LOW ORDER']

,Order_ID,Order_Value,Delivery_Time,Customer_Rating,Distance_KM,Order_Value_Category,Delivery_Time_Category
0,O1,250,30,4,10.0,MEDIUM ORDER,Fast Delivery
1,O2,450,45,3,15.0,HIGH ORDER,Average Delivery
2,O3,120,15,2,5.0,LOW ORDER,Fast Delivery
3,O4,600,60,5,20.0,HIGH ORDER,Slow Delivery
4,O5,300,25,4,12.0,MEDIUM ORDER,Fast Delivery
5,O6,150,10,3,8.0,LOW ORDER,Fast Delivery
6,O7,500,55,2,18.0,HIGH ORDER,Slow Delivery
7,O8,220,35,5,10.0,MEDIUM ORDER,Average Delivery

In [ ]:
#Count of Categories
print(df['Order_Value_Category'].value_counts())
df

Order_Value_Category
MEDIUM ORDER    3
HIGH ORDER      3
LOW ORDER       2
Name: count, dtype: int64

,Order_ID,Order_Value,Delivery_Time,Customer_Rating,Distance_KM,Order_Value_Category,Delivery_Time_Category
0,O1,250,30,4,10.0,MEDIUM ORDER,Fast Delivery
1,O2,450,45,3,15.0,HIGH ORDER,Average Delivery
2,O3,120,15,2,5.0,LOW ORDER,Fast Delivery
3,O4,600,60,5,20.0,HIGH ORDER,Slow Delivery
4,O5,300,25,4,12.0,MEDIUM ORDER,Fast Delivery
5,O6,150,10,3,8.0,LOW ORDER,Fast Delivery
6,O7,500,55,2,18.0,HIGH ORDER,Slow Delivery
7,O8,220,35,5,10.0,MEDIUM ORDER,Average Delivery

In [ ]:
#Sorting
print(df.sort_values(by='Order_Value'))
df

  Order_ID  Order_Value  Delivery_Time  Customer_Rating  Distance_KM  \
2       O3          120             15                2          5.0
5       O6          150             10                3          8.0
7       O8          220             35                5         10.0
0       O1          250             30                4         10.0
4       O5          300             25                4         12.0
1       O2          450             45                3         15.0
6       O7          500             55                2         18.0
3       O4          600             60                5         20.0

  Order_Value_Category Delivery_Time_Category
2            LOW ORDER          Fast Delivery
5            LOW ORDER          Fast Delivery
7         MEDIUM ORDER       Average Delivery
0         MEDIUM ORDER          Fast Delivery
4         MEDIUM ORDER          Fast Delivery
1           HIGH ORDER       Average Delivery
6           HIGH ORDER          Slow Delivery
3           HIGH ORDER          Slow Delivery

,Order_ID,Order_Value,Delivery_Time,Customer_Rating,Distance_KM,Order_Value_Category,Delivery_Time_Category
0,O1,250,30,4,10.0,MEDIUM ORDER,Fast Delivery
1,O2,450,45,3,15.0,HIGH ORDER,Average Delivery
2,O3,120,15,2,5.0,LOW ORDER,Fast Delivery
3,O4,600,60,5,20.0,HIGH ORDER,Slow Delivery
4,O5,300,25,4,12.0,MEDIUM ORDER,Fast Delivery
5,O6,150,10,3,8.0,LOW ORDER,Fast Delivery
6,O7,500,55,2,18.0,HIGH ORDER,Slow Delivery
7,O8,220,35,5,10.0,MEDIUM ORDER,Average Delivery